### ISSUE TITLE
Proposal: put together iOS and Android apps

### ISSUE THREAD

**Issue by llemeurfr** [readium/awesome-readium#3]
Most mobile apps are declined in an iOS + Android variant. Merging the two sections in one would make sense IMO. 
Any thoughts?

**Comment by elvey** [comment]
Looks like it's been done - there's now a "Apps based on Readium Mobile" section with both.
Close?  (Not sure what you meant by "declined". Mistransation of "come in" or "fall into", I presume.)

**Comment by llemeurfr** [comment]
Yes in fact we did the merge of the two sections some months ago and we can close this proposal. Thanks for the reminder.
